-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-03-02 08:27:09 CST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE categories (
    category_id   NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    category_name VARCHAR2(250) NOT NULL,
    category_key  VARCHAR2(250) NOT NULL,
    description   VARCHAR2(4000),
    created_by    VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on    TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by    VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on    TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE categories ADD CONSTRAINT categories_pk PRIMARY KEY ( category_id );

ALTER TABLE categories ADD CONSTRAINT categories_un UNIQUE ( category_key );

CREATE TABLE comments (
    comment_id       NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    rule_set_id      NUMBER NOT NULL,
    rule_id          NUMBER NOT NULL,
    comments         VARCHAR2(4000) NOT NULL,
    workspace_id     NUMBER NOT NULL,
    application_id   NUMBER NOT NULL,
    page_id          NUMBER,
    component_id     VARCHAR2(250),
    column_name      VARCHAR2(250),
    item_name        VARCHAR2(250),
    shared_comp_name VARCHAR2(250),
    created_by       VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on       TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by       VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on       TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE comments ADD CONSTRAINT comments_pk PRIMARY KEY ( comment_id );

CREATE TABLE eval_results (
    eval_result_id   NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    eval_id          NUMBER NOT NULL,
    rule_id          NUMBER NOT NULL,
    application_id   NUMBER,
    page_id          NUMBER,
    component_id     VARCHAR2(250),
    item_name        VARCHAR2(250),
    column_name      VARCHAR2(250),
    shared_comp_name VARCHAR2(250),
    result           CLOB NOT NULL,
    current_value    VARCHAR2(4000),
    valid_values     VARCHAR2(4000),
    created_by       VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on       TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by       VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on       TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE eval_results ADD CONSTRAINT eval_results_pk PRIMARY KEY ( eval_result_id );

CREATE TABLE evals (
    eval_id        NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    workspace_id   NUMBER NOT NULL,
    application_id NUMBER NOT NULL,
    rule_set_id    NUMBER NOT NULL,
    eval_on        TIMESTAMP WITH LOCAL TIME ZONE,
    eval_on_date   DATE NOT NULL,
    eval_by        VARCHAR2(250),
    summary        CLOB,
    job_name       VARCHAR2(250),
    job_status     VARCHAR2(250),
    score          NUMBER,
    created_by     VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on     TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by     VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on     TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE evals ADD CONSTRAINT evals_pk PRIMARY KEY ( eval_id );

CREATE TABLE exceptions (
    exception_id     NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    rule_set_id      NUMBER NOT NULL,
    rule_id          NUMBER NOT NULL,
    exception        VARCHAR2(4000) NOT NULL,
    workspace_id     NUMBER NOT NULL,
    application_id   NUMBER NOT NULL,
    page_id          NUMBER,
    component_id     VARCHAR2(250),
    column_name      VARCHAR2(250),
    item_name        VARCHAR2(250),
    shared_comp_name VARCHAR2(250),
    result           VARCHAR2(250) NOT NULL,
    reason           VARCHAR2(4000),
    current_value    VARCHAR2(4000),
    created_by       VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on       TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by       VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on       TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp,
    actioned_by      VARCHAR2(250),
    actioned_on      TIMESTAMP WITH LOCAL TIME ZONE
)
LOGGING;

ALTER TABLE exceptions ADD CONSTRAINT exceptions_pk PRIMARY KEY ( exception_id );

CREATE TABLE logs (
    log_id     NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    log_type   VARCHAR2(100) NOT NULL,
    log_key    VARCHAR2(250),
    log        VARCHAR2(4000),
    log_clob   CLOB,
    id         VARCHAR2(250),
    id_col     VARCHAR2(250),
    id_table   VARCHAR2(250),
    created_by VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL
)
LOGGING;

ALTER TABLE logs ADD CONSTRAINT logs_pk PRIMARY KEY ( log_id );

CREATE TABLE prefs (
    pref_id     NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    pref_name   VARCHAR2(250) NOT NULL,
    pref_key    VARCHAR2(250) NOT NULL,
    pref_value  VARCHAR2(4000) NOT NULL,
    description VARCHAR2(4000),
    created_by  VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on  TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by  VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on  TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE prefs ADD CONSTRAINT prefs_pk PRIMARY KEY ( pref_id );

ALTER TABLE prefs ADD CONSTRAINT prefs_un UNIQUE ( pref_key );

CREATE TABLE reserved_strings (
    reserved_string_id   NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    reserved_string      VARCHAR2(250) NOT NULL,
    reserved_string_key  VARCHAR2(250) NOT NULL,
    reserved_string_type VARCHAR2(250) NOT NULL,
    description          VARCHAR2(4000),
    active_yn            VARCHAR2(1) DEFAULT ON NULL 'Y' NOT NULL,
    created_by           VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on           TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by           VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on           TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE reserved_strings
    ADD CONSTRAINT reserved_strings_active_yn CHECK ( active_yn IN ( 'N', 'Y' ) );

ALTER TABLE reserved_strings ADD CONSTRAINT reserved_strings_pk PRIMARY KEY ( reserved_string_id );

ALTER TABLE reserved_strings ADD CONSTRAINT reserved_strings_un UNIQUE ( reserved_string_key,
                                                                         reserved_string_type );

CREATE TABLE risks (
    risk_id     NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    risk_code   VARCHAR2(250) NOT NULL,
    risk_name   VARCHAR2(250) NOT NULL,
    url         VARCHAR2(250) NOT NULL,
    description VARCHAR2(4000),
    created_by  VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on  TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by  VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on  TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE risks ADD CONSTRAINT risks_pk PRIMARY KEY ( risk_id );

CREATE TABLE rule_criteria (
    rule_criteria_id      NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    rule_criteria_name    VARCHAR2(250) NOT NULL,
    rule_criteria_key     VARCHAR2(250) NOT NULL,
    rule_criteria_type_id NUMBER NOT NULL,
    rule_criteria_sql     VARCHAR2(4000) NOT NULL,
    reason                VARCHAR2(4000),
    description           VARCHAR2(4000),
    active_yn             VARCHAR2(1) DEFAULT ON NULL 'Y' NOT NULL,
    internal_yn           VARCHAR2(1) DEFAULT ON NULL 'N' NOT NULL,
    created_by            VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on            TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by            VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on            TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE rule_criteria
    ADD CONSTRAINT rule_criteria_active_yn CHECK ( active_yn IN ( 'N', 'Y' ) );

ALTER TABLE rule_criteria
    ADD CONSTRAINT rule_criteria_internal_yn CHECK ( internal_yn IN ( 'N', 'Y' ) );

ALTER TABLE rule_criteria ADD CONSTRAINT rule_criteria_pk PRIMARY KEY ( rule_criteria_id );

ALTER TABLE rule_criteria ADD CONSTRAINT rule_criteria_un UNIQUE ( rule_criteria_key );

CREATE TABLE rule_criteria_types (
    rule_criteria_type_id   NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    rule_criteria_type_name VARCHAR2(250) NOT NULL,
    rule_criteria_type_key  VARCHAR2(250) NOT NULL,
    active_yn               VARCHAR2(1) DEFAULT ON NULL 'Y' NOT NULL,
    internal_yn             VARCHAR2(1) DEFAULT ON NULL 'N' NOT NULL,
    description             VARCHAR2(4000),
    created_by              VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on              TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by              VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on              TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE rule_criteria_types
    ADD CONSTRAINT rule_criteria_types_active_yn CHECK ( active_yn IN ( 'N', 'Y' ) );

ALTER TABLE rule_criteria_types
    ADD CONSTRAINT rule_criteria_types_int_yn CHECK ( internal_yn IN ( 'N', 'Y' ) );

ALTER TABLE rule_criteria_types ADD CONSTRAINT rule_criteria_types_pk PRIMARY KEY ( rule_criteria_type_id );

ALTER TABLE rule_criteria_types ADD CONSTRAINT rule_criteria_types_un UNIQUE ( rule_criteria_type_key );

CREATE TABLE rule_set_rules (
    rule_set_rule_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    rule_set_id      NUMBER NOT NULL,
    rule_id          NUMBER NOT NULL,
    created_by       VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on       TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by       VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on       TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE rule_set_rules ADD CONSTRAINT rule_set_rules_pk PRIMARY KEY ( rule_set_rule_id );

ALTER TABLE rule_set_rules ADD CONSTRAINT rule_set_rules_un UNIQUE ( rule_set_id,
                                                                     rule_id );

CREATE TABLE rule_set_types (
    rule_set_type_id   NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    rule_set_type_name VARCHAR2(250) NOT NULL,
    rule_set_type_key  VARCHAR2(250) NOT NULL,
    description        VARCHAR2(4000),
    created_by         VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on         TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by         VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on         TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE rule_set_types ADD CONSTRAINT rule_set_types_pk PRIMARY KEY ( rule_set_type_id );

ALTER TABLE rule_set_types ADD CONSTRAINT rule_set_types_un UNIQUE ( rule_set_type_key );

CREATE TABLE rule_sets (
    rule_set_id      NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    rule_set_type_id NUMBER NOT NULL,
    rule_set_name    VARCHAR2(250) NOT NULL,
    rule_set_key     VARCHAR2(250) NOT NULL,
    apex_version     NUMBER NOT NULL,
    active_yn        VARCHAR2(1) DEFAULT ON NULL 'Y' NOT NULL,
    internal_yn      VARCHAR2(1) DEFAULT ON NULL 'N' NOT NULL,
    description      VARCHAR2(4000),
    created_by       VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on       TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by       VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on       TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE rule_sets
    ADD CONSTRAINT rule_sets_active_yn CHECK ( active_yn IN ( 'N', 'Y' ) );

ALTER TABLE rule_sets
    ADD CONSTRAINT rule_sets_internal_yn CHECK ( internal_yn IN ( 'N', 'Y' ) );

ALTER TABLE rule_sets ADD CONSTRAINT rule_sets_pk PRIMARY KEY ( rule_set_id );

ALTER TABLE rule_sets ADD CONSTRAINT rule_sets_un UNIQUE ( rule_set_key );

CREATE TABLE rule_severity (
    rule_severity_id   NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    rule_severity_name VARCHAR2(250) NOT NULL,
    rule_severity_key  VARCHAR2(250) NOT NULL,
    seq                NUMBER NOT NULL,
    description        VARCHAR2(4000),
    created_by         VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on         TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by         VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on         TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE rule_severity ADD CONSTRAINT rule_severity_pk PRIMARY KEY ( rule_severity_id );

ALTER TABLE rule_severity ADD CONSTRAINT rule_severity_un UNIQUE ( rule_severity_key );

CREATE TABLE rules (
    rule_id               NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    rule_name             VARCHAR2(250) NOT NULL,
    rule_key              VARCHAR2(250) NOT NULL,
    category_id           NUMBER NOT NULL,
    risk_id               NUMBER,
    rule_severity_id      NUMBER NOT NULL,
    rule_type             VARCHAR2(100) NOT NULL,
    impact                VARCHAR2(100),
    apex_version          NUMBER NOT NULL,
    view_name             VARCHAR2(250),
    column_to_evaluate    VARCHAR2(250),
    component_id          VARCHAR2(250),
    column_name           VARCHAR2(250),
    item_name             VARCHAR2(250),
    shared_comp_name      VARCHAR2(250),
    operand               VARCHAR2(100),
    val_char              VARCHAR2(4000),
    val_number            NUMBER,
    case_sensitive_yn     VARCHAR2(1) DEFAULT ON NULL 'N',
    rule_criteria_type_id NUMBER,
    additional_where      VARCHAR2(4000),
    custom_query          VARCHAR2(4000),
    active_yn             VARCHAR2(1) DEFAULT ON NULL 'Y' NOT NULL,
    internal_yn           VARCHAR2(1) DEFAULT ON NULL 'N' NOT NULL,
    help_url              VARCHAR2(4000),
    builder_url           VARCHAR2(4000),
    info                  CLOB,
    fix                   CLOB,
    time_to_fix           NUMBER,
    description           VARCHAR2(4000),
    created_by            VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on            TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by            VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on            TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE rules
    ADD CONSTRAINT rules_case_sensitive_yn CHECK ( case_sensitive_yn IN ( 'N', 'Y' ) );

ALTER TABLE rules
    ADD CONSTRAINT rules_active_yn CHECK ( active_yn IN ( 'N', 'Y' ) );

ALTER TABLE rules
    ADD CONSTRAINT rules_internal_yn CHECK ( internal_yn IN ( 'N', 'Y' ) );

ALTER TABLE rules ADD CONSTRAINT rules_pk PRIMARY KEY ( rule_id );

ALTER TABLE rules ADD CONSTRAINT rules_un UNIQUE ( rule_key,
                                                   apex_version );

CREATE TABLE shared_comp_views (
    shared_comp_view_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    shared_comp_view    VARCHAR2(250) NOT NULL,
    shared_comp_type    VARCHAR2(250) NOT NULL,
    description         VARCHAR2(4000),
    created_by          VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on          TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by          VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on          TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE shared_comp_views ADD CONSTRAINT shared_comp_views_pk PRIMARY KEY ( shared_comp_view_id );

ALTER TABLE shared_comp_views ADD CONSTRAINT shared_comp_views_un UNIQUE ( shared_comp_view );

ALTER TABLE comments
    ADD CONSTRAINT c_rule_sets_fk FOREIGN KEY ( rule_set_id )
        REFERENCES rule_sets ( rule_set_id )
    NOT DEFERRABLE;

ALTER TABLE comments
    ADD CONSTRAINT c_rules_fk FOREIGN KEY ( rule_id )
        REFERENCES rules ( rule_id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE evals
    ADD CONSTRAINT e_rule_sets_fk FOREIGN KEY ( rule_set_id )
        REFERENCES rule_sets ( rule_set_id )
    NOT DEFERRABLE;

ALTER TABLE exceptions
    ADD CONSTRAINT e_rule_sets_fkv2 FOREIGN KEY ( rule_set_id )
        REFERENCES rule_sets ( rule_set_id )
    NOT DEFERRABLE;

ALTER TABLE exceptions
    ADD CONSTRAINT e_rules_fk FOREIGN KEY ( rule_id )
        REFERENCES rules ( rule_id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE eval_results
    ADD CONSTRAINT er_evals_fk FOREIGN KEY ( eval_id )
        REFERENCES evals ( eval_id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE eval_results
    ADD CONSTRAINT er_rules_fk FOREIGN KEY ( rule_id )
        REFERENCES rules ( rule_id )
    NOT DEFERRABLE;

ALTER TABLE rules
    ADD CONSTRAINT r_categories_fk FOREIGN KEY ( category_id )
        REFERENCES categories ( category_id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE rules
    ADD CONSTRAINT r_risks_fk FOREIGN KEY ( risk_id )
        REFERENCES risks ( risk_id )
    NOT DEFERRABLE;

ALTER TABLE rules
    ADD CONSTRAINT r_rule_criteria_type_fk FOREIGN KEY ( rule_criteria_type_id )
        REFERENCES rule_criteria_types ( rule_criteria_type_id )
    NOT DEFERRABLE;

ALTER TABLE rules
    ADD CONSTRAINT r_rule_severity_fk FOREIGN KEY ( rule_severity_id )
        REFERENCES rule_severity ( rule_severity_id )
    NOT DEFERRABLE;

ALTER TABLE rule_criteria
    ADD CONSTRAINT rc_rule_criteria_types_fk FOREIGN KEY ( rule_criteria_type_id )
        REFERENCES rule_criteria_types ( rule_criteria_type_id )
    NOT DEFERRABLE;

ALTER TABLE rule_sets
    ADD CONSTRAINT rs_rule_set_types_fk FOREIGN KEY ( rule_set_type_id )
        REFERENCES rule_set_types ( rule_set_type_id )
    NOT DEFERRABLE;

ALTER TABLE rule_set_rules
    ADD CONSTRAINT rule_set_rules_rule_sets_fk FOREIGN KEY ( rule_set_id )
        REFERENCES rule_sets ( rule_set_id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE rule_set_rules
    ADD CONSTRAINT rule_set_rules_rules_fk FOREIGN KEY ( rule_id )
        REFERENCES rules ( rule_id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

CREATE OR REPLACE TRIGGER BU_CATEGORIES 
    BEFORE UPDATE ON CATEGORIES 
    FOR EACH ROW 
begin
:new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
:new.updated_on := systimestamp;
end; 
/

CREATE OR REPLACE TRIGGER BU_COMMENTS 
    BEFORE UPDATE ON COMMENTS 
    FOR EACH ROW 
begin
:new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
:new.updated_on := systimestamp;
end; 
/

CREATE OR REPLACE TRIGGER BU_EVAL_RESULTS 
    BEFORE UPDATE ON EVAL_RESULTS 
    FOR EACH ROW 
begin
:new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
:new.updated_on := systimestamp;
end; 
/

CREATE OR REPLACE TRIGGER BU_EVALS 
    BEFORE UPDATE ON EVALS 
    FOR EACH ROW 
begin
:new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
:new.updated_on := systimestamp;
end; 
/

CREATE OR REPLACE TRIGGER BU_EXCEPTIONS 
    BEFORE UPDATE ON EXCEPTIONS 
    FOR EACH ROW 
begin
:new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
:new.updated_on := systimestamp;
end; 
/

CREATE OR REPLACE TRIGGER BU_PREFS 
    BEFORE UPDATE ON PREFS 
    FOR EACH ROW 
begin
:new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
:new.updated_on := systimestamp;
end; 
/

CREATE OR REPLACE TRIGGER BU_RESERVED_STRINGS 
    BEFORE UPDATE ON RESERVED_STRINGS 
    FOR EACH ROW 
begin
:new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
:new.updated_on := systimestamp;
end; 
/

CREATE OR REPLACE TRIGGER BU_RISKS 
    BEFORE UPDATE ON RISKS 
    FOR EACH ROW 
begin
:new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
:new.updated_on := systimestamp;
end; 
/

CREATE OR REPLACE TRIGGER BU_RULE_CRITERIA 
    BEFORE UPDATE ON RULE_CRITERIA 
    FOR EACH ROW 
begin
:new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
:new.updated_on := systimestamp;
end; 
/

CREATE OR REPLACE TRIGGER BU_RULE_CRITERIA_TYPES 
    BEFORE UPDATE ON RULE_CRITERIA_TYPES 
    FOR EACH ROW 
begin
:new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
:new.updated_on := systimestamp;
end; 
/

CREATE OR REPLACE TRIGGER BU_RULE_SET_RULES 
    BEFORE UPDATE ON RULE_SET_RULES 
    FOR EACH ROW 
begin
:new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
:new.updated_on := systimestamp;
end; 
/

CREATE OR REPLACE TRIGGER BU_RULE_SET_TYPES 
    BEFORE UPDATE ON RULE_SET_TYPES 
    FOR EACH ROW 
begin
:new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
:new.updated_on := systimestamp;
end; 
/

CREATE OR REPLACE TRIGGER BU_RULE_SETS 
    BEFORE UPDATE ON RULE_SETS 
    FOR EACH ROW 
begin
:new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
:new.updated_on := systimestamp;
end; 
/

CREATE OR REPLACE TRIGGER BU_RULE_SEVERITY 
    BEFORE UPDATE ON RULE_SEVERITY 
    FOR EACH ROW 
begin
:new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
:new.updated_on := systimestamp;
end; 
/

CREATE OR REPLACE TRIGGER BU_RULES 
    BEFORE UPDATE ON RULES 
    FOR EACH ROW 
begin
:new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
:new.updated_on := systimestamp;
end; 
/

CREATE OR REPLACE TRIGGER BU_SHARED_COMP_VIEWS 
    BEFORE UPDATE ON SHARED_COMP_VIEWS 
    FOR EACH ROW 
begin
:new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
:new.updated_on := systimestamp;
end; 
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            17
-- CREATE INDEX                             0
-- ALTER TABLE                             53
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                          16
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
