-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-02-12 14:06:22 CST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE categories (
    category_id       NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    classification_id NUMBER NOT NULL,
    category_name     VARCHAR2(250) NOT NULL,
    category_key      VARCHAR2(250) NOT NULL,
    created_by        VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on        TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by        VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on        TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE categories ADD CONSTRAINT categories_pk PRIMARY KEY ( category_id );

ALTER TABLE categories ADD CONSTRAINT categories_un UNIQUE ( category_key );

CREATE TABLE classifications (
    classification_id   NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    classification_name VARCHAR2(250) NOT NULL,
    classification_key  VARCHAR2(250) NOT NULL,
    created_by          VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on          TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by          VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on          TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE classifications ADD CONSTRAINT classifications_pk PRIMARY KEY ( classification_id );

ALTER TABLE classifications ADD CONSTRAINT classifications_un UNIQUE ( classification_key );

CREATE TABLE eval_results (
    eval_result_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    eval_id        NUMBER NOT NULL,
    rule_id        NUMBER NOT NULL,
    application_id NUMBER,
    page_id        NUMBER,
    component_id   VARCHAR2(250),
    column_name    VARCHAR2(250),
    result         VARCHAR2(100) NOT NULL,
    result_details VARCHAR2(4000),
    current_value  VARCHAR2(4000),
    valid_values   VARCHAR2(4000),
    created_by     VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on     TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by     VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on     TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE eval_results ADD CONSTRAINT eval_results_pk PRIMARY KEY ( eval_result_id );

CREATE TABLE evals (
    eval_id        NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    workspace_id   NUMBER NOT NULL,
    application_id NUMBER NOT NULL,
    rule_set_id    NUMBER NOT NULL,
    eval_on        TIMESTAMP WITH LOCAL TIME ZONE,
    eval_by        VARCHAR2(250),
    summary        CLOB,
    created_by     VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on     TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by     VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on     TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp,
    current_value  VARCHAR2(4000),
    valid_values   VARCHAR2(4000)
)
LOGGING;

ALTER TABLE evals ADD CONSTRAINT evals_pk PRIMARY KEY ( eval_id );

CREATE TABLE rule_set_rules (
    rule_set_rule_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    rule_set_id      NUMBER NOT NULL,
    rule_id          NUMBER NOT NULL,
    created_by       VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on       TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by       VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on       TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE rule_set_rules ADD CONSTRAINT rule_set_rules_pk PRIMARY KEY ( rule_set_rule_id );

ALTER TABLE rule_set_rules ADD CONSTRAINT rule_set_rules_un UNIQUE ( rule_set_id,
                                                                     rule_id );

CREATE TABLE rule_set_types (
    rule_set_type_id   NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    rule_set_type_name VARCHAR2(250) NOT NULL,
    rule_set_type_key  VARCHAR2(250) NOT NULL,
    created_by         VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on         TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by         VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on         TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE rule_set_types ADD CONSTRAINT rule_set_types_pk PRIMARY KEY ( rule_set_type_id );

ALTER TABLE rule_set_types ADD CONSTRAINT rule_set_types_un UNIQUE ( rule_set_type_key );

CREATE TABLE rule_sets (
    rule_set_id      NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    rule_set_type_id NUMBER NOT NULL,
    rule_set_name    VARCHAR2(250) NOT NULL,
    rule_set_key     VARCHAR2(250) NOT NULL,
    apex_version     NUMBER NOT NULL,
    active_yn        VARCHAR2(1) DEFAULT ON NULL 'Y' NOT NULL,
    internal_yn      VARCHAR2(1) DEFAULT ON NULL 'N' NOT NULL,
    description      VARCHAR2(4000),
    created_by       VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on       TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by       VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on       TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE rule_sets
    ADD CONSTRAINT rule_sets_active_yn CHECK ( active_yn IN ( 'N', 'Y' ) );

ALTER TABLE rule_sets
    ADD CONSTRAINT rule_sets_internal_yn CHECK ( internal_yn IN ( 'N', 'Y' ) );

ALTER TABLE rule_sets ADD CONSTRAINT rule_sets_pk PRIMARY KEY ( rule_set_id );

ALTER TABLE rule_sets ADD CONSTRAINT rule_sets_un UNIQUE ( rule_set_key );

CREATE TABLE rule_severity (
    rule_severity_id   NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    rule_severity_name VARCHAR2(250) NOT NULL,
    rule_severity_key  VARCHAR2(250) NOT NULL,
    seq                NUMBER NOT NULL,
    created_by         VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on         TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by         VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on         TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE rule_severity ADD CONSTRAINT rule_severity_pk PRIMARY KEY ( rule_severity_id );

CREATE TABLE rules (
    rule_id           NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    rule_name         VARCHAR2(250) NOT NULL,
    rule_key          VARCHAR2(250) NOT NULL,
    category_id       NUMBER NOT NULL,
    rule_type         VARCHAR2(100) NOT NULL,
    rule_severity_id  NUMBER NOT NULL,
    impact            VARCHAR2(100),
    apex_version      NUMBER NOT NULL,
    view_name         VARCHAR2(250),
    column_name       VARCHAR2(250),
    operand           VARCHAR2(100),
    val_char          VARCHAR2(4000),
    val_number        NUMBER,
    case_sensitive_yn VARCHAR2(1) DEFAULT ON NULL 'N',
    active_yn         VARCHAR2(1) DEFAULT ON NULL 'Y' NOT NULL,
    internal_yn       VARCHAR2(1) DEFAULT ON NULL 'N' NOT NULL,
    help_url          VARCHAR2(4000),
    builder_url       VARCHAR2(4000),
    info              CLOB,
    fix               CLOB,
    time_to_fix       NUMBER,
    created_by        VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on        TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by        VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on        TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE rules
    ADD CONSTRAINT rules_case_sensitive_yn CHECK ( case_sensitive_yn IN ( 'N', 'Y' ) );

ALTER TABLE rules
    ADD CONSTRAINT rules_active_yn CHECK ( active_yn IN ( 'N', 'Y' ) );

ALTER TABLE rules
    ADD CONSTRAINT rules_internal_yn CHECK ( internal_yn IN ( 'N', 'Y' ) );

ALTER TABLE rules ADD CONSTRAINT rules_pk PRIMARY KEY ( rule_id );

ALTER TABLE rules ADD CONSTRAINT rules_un UNIQUE ( rule_key,
                                                   apex_version );

ALTER TABLE categories
    ADD CONSTRAINT categories_classifications_fk FOREIGN KEY ( classification_id )
        REFERENCES classifications ( classification_id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE eval_results
    ADD CONSTRAINT eval_results_evals_fk FOREIGN KEY ( eval_id )
        REFERENCES evals ( eval_id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE eval_results
    ADD CONSTRAINT eval_results_rules_fk FOREIGN KEY ( rule_id )
        REFERENCES rules ( rule_id )
    NOT DEFERRABLE;

ALTER TABLE evals
    ADD CONSTRAINT evals_rule_sets_fk FOREIGN KEY ( rule_set_id )
        REFERENCES rule_sets ( rule_set_id )
    NOT DEFERRABLE;

ALTER TABLE rule_set_rules
    ADD CONSTRAINT rule_set_rules_rule_sets_fk FOREIGN KEY ( rule_set_id )
        REFERENCES rule_sets ( rule_set_id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE rule_set_rules
    ADD CONSTRAINT rule_set_rules_rules_fk FOREIGN KEY ( rule_id )
        REFERENCES rules ( rule_id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE rule_sets
    ADD CONSTRAINT rule_sets_rule_set_types_fk FOREIGN KEY ( rule_set_type_id )
        REFERENCES rule_set_types ( rule_set_type_id )
    NOT DEFERRABLE;

ALTER TABLE rules
    ADD CONSTRAINT rules_categories_fk FOREIGN KEY ( category_id )
        REFERENCES categories ( category_id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE rules
    ADD CONSTRAINT rules_rule_severity_fk FOREIGN KEY ( rule_severity_id )
        REFERENCES rule_severity ( rule_severity_id )
    NOT DEFERRABLE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             0
-- ALTER TABLE                             29
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
